"""Markdown report generator for CodeScope analysis results."""

from datetime import datetime
from pathlib import Path
from typing import Optional

from codescope.core.models import AnalysisResults


class MarkdownReporter:
    """Generate Markdown reports from analysis results."""

    def generate(self, results: AnalysisResults, output_path: Optional[Path] = None) -> str:
        """Generate Markdown report from analysis results."""
        md = self._render_markdown(results)

        if output_path:
            output_path.write_text(md, encoding='utf-8')

        return md

    def _render_markdown(self, results: AnalysisResults) -> str:
        """Render Markdown from results."""
        # Issue counts
        bugs = sum(1 for i in results.all_issues if i.issue_type.value == 'BUG')
        vulns = sum(1 for i in results.all_issues if i.issue_type.value == 'VULNERABILITY')
        smells = sum(1 for i in results.all_issues if i.issue_type.value == 'CODE_SMELL')

        # Severity counts
        blockers = sum(1 for i in results.all_issues if i.severity.value == 'BLOCKER')
        criticals = sum(1 for i in results.all_issues if i.severity.value == 'CRITICAL')
        majors = sum(1 for i in results.all_issues if i.severity.value == 'MAJOR')
        minors = sum(1 for i in results.all_issues if i.severity.value == 'MINOR')
        infos = sum(1 for i in results.all_issues if i.severity.value == 'INFO')

        # Quality gate status
        qg_status = "PASSED"
        if results.quality_gate_status:
            qg_status = results.quality_gate_status.value

        qg_emoji = "✅" if qg_status == "PASSED" else "❌" if qg_status == "FAILED" else "⚠️"

        # Start building markdown
        md = f"""# CodeScope Analysis Report

**Project:** {results.project_name}
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Files Analyzed:** {results.files_analyzed}
**Duration:** {results.duration_seconds:.2f}s

---

## {qg_emoji} Quality Gate: {qg_status}

---

## Summary

| Metric | Count |
|--------|-------|
| **Total Issues** | {len(results.all_issues)} |
| Bugs | {bugs} |
| Vulnerabilities | {vulns} |
| Code Smells | {smells} |

### Issues by Severity

| Severity | Count |
|----------|-------|
| 🔴 Blocker | {blockers} |
| 🟠 Critical | {criticals} |
| 🟡 Major | {majors} |
| 🔵 Minor | {minors} |
| ⚪ Info | {infos} |

---

## Project Metrics

| Metric | Value |
|--------|-------|
| Lines of Code | {sum(f.lines_of_code for f in results.file_metrics):,} |
| Comment Lines | {sum(f.comment_lines for f in results.file_metrics):,} |
| Functions | {sum(f.functions for f in results.file_metrics):,} |
| Classes | {sum(f.classes for f in results.file_metrics):,} |
| Avg Complexity | {sum(f.complexity for f in results.file_metrics) / max(len(results.file_metrics), 1):.1f} |

---

## Issues

"""

        # Group issues by severity
        for severity in ['BLOCKER', 'CRITICAL', 'MAJOR', 'MINOR', 'INFO']:
            issues = [i for i in results.all_issues if i.severity.value == severity]
            if issues:
                md += f"### {severity} ({len(issues)})\n\n"

                for issue in issues:
                    md += f"- **{issue.rule_name}** (`{issue.rule_id}`)\n"
                    md += f"  - {issue.message}\n"
                    md += f"  - 📍 `{issue.location.file_path}:{issue.location.start_line}`\n"
                    if issue.snippet:
                        md += f"  ```\n  {issue.snippet}\n  ```\n"
                    md += "\n"

        # Top files with issues
        md += """---

## Files with Most Issues

| File | Issues | Lines | Complexity |
|------|--------|-------|------------|
"""

        sorted_files = sorted(results.file_metrics, key=lambda f: f.issues_count, reverse=True)
        for fm in sorted_files[:10]:
            if fm.issues_count > 0:
                md += f"| `{fm.file_path}` | {fm.issues_count} | {fm.lines_of_code} | {fm.complexity} |\n"

        # Footer
        md += f"""
---

*Generated by [CodeScope](https://github.com/codescope/codescope) v0.1.0*
"""

        return md
