"""Generate CI/CD pipeline configs for popular platforms."""

from __future__ import annotations

from typing import Optional


def generate_github_actions(
    project_name: str = "my-project",
    quality_gate: bool = True,
    coverage_threshold: int = 80,
    fail_on_vulnerabilities: bool = True,
    ai_vetting: bool = False,
    schedule: Optional[str] = None,
) -> str:
    """Generate a GitHub Actions workflow YAML for CodeScope."""
    schedule_block = ""
    if schedule:
        schedule_block = f"\n  schedule:\n    - cron: '{schedule}'"

    ai_vet_step = ""
    if ai_vetting:
        ai_vet_step = """
      - name: AI Code Vetting
        run: codescope ai-vet . --format json -o ai-vet-results.json --fail-on-risk high

      - name: Upload AI Vet Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-vet-results
          path: ai-vet-results.json
"""

    gate_step = ""
    if quality_gate:
        gate_step = f"""
      - name: Quality Gate
        run: |
          echo "::group::Quality Gate Evaluation"
          ISSUES=$(python -c "
          import json
          with open('codescope-results.json') as f:
              data = json.load(f)
          s = data.get('summary', {{}})
          blockers = s.get('blocker_count', 0)
          critical = s.get('critical_count', 0)
          vulns = s.get('vulnerability_count', 0)
          print(f'Blockers: {{blockers}}, Critical: {{critical}}, Vulnerabilities: {{vulns}}')
          if blockers > 0 or critical > 0{' or vulns > 0' if fail_on_vulnerabilities else ''}:
              print('QUALITY_GATE=FAILED')
              raise SystemExit(1)
          print('QUALITY_GATE=PASSED')
          ")
          echo "$ISSUES"
          echo "::endgroup::"
"""

    return f"""# CodeScope Analysis for {project_name}
# Auto-generated by CodeScope CI/CD Integration

name: CodeScope Analysis

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]{schedule_block}

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  codescope-scan:
    name: CodeScope Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install CodeScope
        run: pip install codescope

      - name: Run CodeScope Scan
        run: |
          codescope scan . --format json -o codescope-results.json
          codescope scan . --format sarif -o codescope-results.sarif

      - name: Dependency Vulnerability Check
        run: codescope dependencies . --format json -o dep-results.json{' --fail-on critical' if fail_on_vulnerabilities else ''}

      - name: Coverage Check
        if: always()
        run: codescope coverage . --threshold {coverage_threshold} || true
{ai_vet_step}{gate_step}
      - name: Upload SARIF Results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: codescope-results.sarif

      - name: Upload Analysis Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codescope-results
          path: |
            codescope-results.json
            codescope-results.sarif
            dep-results.json

      - name: Comment PR with Results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let body = '## CodeScope Analysis Results\\n\\n';
            try {{
              const data = JSON.parse(fs.readFileSync('codescope-results.json', 'utf8'));
              const s = data.summary || {{}};
              body += `| Metric | Count |\\n|--------|-------|\\n`;
              body += `| Bugs | ${{s.bug_count || 0}} |\\n`;
              body += `| Vulnerabilities | ${{s.vulnerability_count || 0}} |\\n`;
              body += `| Code Smells | ${{s.code_smell_count || 0}} |\\n`;
              body += `| Blockers | ${{s.blocker_count || 0}} |\\n`;
            }} catch (e) {{
              body += '> Analysis results unavailable\\n';
            }}
            github.rest.issues.createComment({{
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            }});
"""


def generate_gitlab_ci(
    project_name: str = "my-project",
    quality_gate: bool = True,
    coverage_threshold: int = 80,
    fail_on_vulnerabilities: bool = True,
    ai_vetting: bool = False,
) -> str:
    """Generate a GitLab CI YAML for CodeScope."""
    ai_vet_job = ""
    if ai_vetting:
        ai_vet_job = """
codescope-ai-vet:
  stage: test
  script:
    - pip install codescope
    - codescope ai-vet . --format json -o ai-vet-results.json --fail-on-risk high
  artifacts:
    paths:
      - ai-vet-results.json
    when: always
  allow_failure: true
"""

    gate_script = ""
    if quality_gate:
        gate_script = f"""
codescope-gate:
  stage: gate
  script:
    - pip install codescope
    - python -c "
      import json;
      data = json.load(open('codescope-results.json'));
      s = data.get('summary', {{}});
      blockers = s.get('blocker_count', 0);
      critical = s.get('critical_count', 0);
      vulns = s.get('vulnerability_count', 0);
      failed = blockers > 0 or critical > 0{' or vulns > 0' if fail_on_vulnerabilities else ''};
      print(f'Quality Gate: {{\"FAILED\" if failed else \"PASSED\"}}');
      raise SystemExit(1) if failed else None
      "
  dependencies:
    - codescope-scan
"""

    return f"""# CodeScope Analysis for {project_name}
# Auto-generated by CodeScope CI/CD Integration

stages:
  - test
  - gate

codescope-scan:
  stage: test
  image: python:3.11-slim
  script:
    - pip install codescope
    - codescope scan . --format json -o codescope-results.json
    - codescope scan . --format sarif -o codescope-results.sarif
  artifacts:
    paths:
      - codescope-results.json
      - codescope-results.sarif
    reports:
      sast: codescope-results.sarif
    when: always

codescope-dependencies:
  stage: test
  image: python:3.11-slim
  script:
    - pip install codescope
    - codescope dependencies . --format json -o dep-results.json{' --fail-on critical' if fail_on_vulnerabilities else ''}
  artifacts:
    paths:
      - dep-results.json
    when: always
  allow_failure: {'false' if fail_on_vulnerabilities else 'true'}

codescope-coverage:
  stage: test
  image: python:3.11-slim
  script:
    - pip install codescope
    - codescope coverage . --threshold {coverage_threshold}
  allow_failure: true
{ai_vet_job}{gate_script}"""


def generate_jenkins(
    project_name: str = "my-project",
    quality_gate: bool = True,
    coverage_threshold: int = 80,
    fail_on_vulnerabilities: bool = True,
) -> str:
    """Generate a Jenkinsfile for CodeScope."""
    gate_stage = ""
    if quality_gate:
        gate_stage = f"""
        stage('Quality Gate') {{
            steps {{
                script {{
                    def results = readJSON file: 'codescope-results.json'
                    def summary = results.summary ?: [:]
                    def blockers = summary.blocker_count ?: 0
                    def critical = summary.critical_count ?: 0
                    def vulns = summary.vulnerability_count ?: 0

                    echo "Blockers: ${{blockers}}, Critical: ${{critical}}, Vulnerabilities: ${{vulns}}"

                    if (blockers > 0 || critical > 0{' || vulns > 0' if fail_on_vulnerabilities else ''}) {{
                        error 'Quality Gate FAILED'
                    }}
                    echo 'Quality Gate PASSED'
                }}
            }}
        }}"""

    return f"""// CodeScope Analysis for {project_name}
// Auto-generated by CodeScope CI/CD Integration

pipeline {{
    agent any

    environment {{
        CODESCOPE_COVERAGE_THRESHOLD = '{coverage_threshold}'
    }}

    stages {{
        stage('Checkout') {{
            steps {{
                checkout scm
            }}
        }}

        stage('Install CodeScope') {{
            steps {{
                sh 'pip install codescope'
            }}
        }}

        stage('CodeScope Scan') {{
            steps {{
                sh 'codescope scan . --format json -o codescope-results.json'
                sh 'codescope scan . --format sarif -o codescope-results.sarif'
            }}
        }}

        stage('Dependency Check') {{
            steps {{
                sh 'codescope dependencies . --format json -o dep-results.json{' --fail-on critical' if fail_on_vulnerabilities else ''}'
            }}
        }}

        stage('Coverage Check') {{
            steps {{
                sh "codescope coverage . --threshold ${{CODESCOPE_COVERAGE_THRESHOLD}} || true"
            }}
        }}
{gate_stage}
    }}

    post {{
        always {{
            archiveArtifacts artifacts: '*.json,*.sarif', allowEmptyArchive: true
            recordIssues tools: [sarif(pattern: 'codescope-results.sarif')]
        }}
        failure {{
            echo 'CodeScope analysis detected issues.'
        }}
    }}
}}
"""


def generate_azure_pipelines(
    project_name: str = "my-project",
    quality_gate: bool = True,
    coverage_threshold: int = 80,
    fail_on_vulnerabilities: bool = True,
) -> str:
    """Generate an Azure Pipelines YAML for CodeScope."""
    gate_step = ""
    if quality_gate:
        gate_step = f"""
    - script: |
        python -c "
        import json, sys
        data = json.load(open('codescope-results.json'))
        s = data.get('summary', {{}})
        blockers = s.get('blocker_count', 0)
        critical = s.get('critical_count', 0)
        vulns = s.get('vulnerability_count', 0)
        print(f'Blockers: {{blockers}}, Critical: {{critical}}, Vulnerabilities: {{vulns}}')
        if blockers > 0 or critical > 0{' or vulns > 0' if fail_on_vulnerabilities else ''}:
            print('##vso[task.logissue type=error]Quality Gate FAILED')
            sys.exit(1)
        print('Quality Gate PASSED')
        "
      displayName: Quality Gate"""

    return f"""# CodeScope Analysis for {project_name}
# Auto-generated by CodeScope CI/CD Integration

trigger:
  branches:
    include:
      - main
      - master
      - develop

pr:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'
      displayName: Set up Python

    - script: pip install codescope
      displayName: Install CodeScope

    - script: |
        codescope scan . --format json -o codescope-results.json
        codescope scan . --format sarif -o codescope-results.sarif
      displayName: CodeScope Scan

    - script: codescope dependencies . --format json -o dep-results.json{' --fail-on critical' if fail_on_vulnerabilities else ''}
      displayName: Dependency Check

    - script: codescope coverage . --threshold {coverage_threshold} || true
      displayName: Coverage Check
{gate_step}
    - task: PublishBuildArtifacts@1
      condition: always()
      inputs:
        pathToPublish: codescope-results.json
        artifactName: codescope-results
      displayName: Publish Results

    - task: PublishBuildArtifacts@1
      condition: always()
      inputs:
        pathToPublish: codescope-results.sarif
        artifactName: codescope-sarif
      displayName: Publish SARIF
"""
